package com.gofind.gofind.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MaisonAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaisonAllPropertiesEquals(Maison expected, Maison actual) {
        assertMaisonAutoGeneratedPropertiesEquals(expected, actual);
        assertMaisonAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaisonAllUpdatablePropertiesEquals(Maison expected, Maison actual) {
        assertMaisonUpdatableFieldsEquals(expected, actual);
        assertMaisonUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaisonAutoGeneratedPropertiesEquals(Maison expected, Maison actual) {
        assertThat(expected)
            .as("Verify Maison auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaisonUpdatableFieldsEquals(Maison expected, Maison actual) {
        assertThat(expected)
            .as("Verify Maison relevant properties")
            .satisfies(e -> assertThat(e.getAdresse()).as("check adresse").isEqualTo(actual.getAdresse()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getImage()).as("check image").isEqualTo(actual.getImage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaisonUpdatableRelationshipsEquals(Maison expected, Maison actual) {
        assertThat(expected)
            .as("Verify Maison relationships")
            .satisfies(e -> assertThat(e.getProprietaire()).as("check proprietaire").isEqualTo(actual.getProprietaire()));
    }
}
